name: myportfolio
description: My profolio page.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  image_path: 'assets/YClogo.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
      - assets/

  fonts:
    - family: Google
      fonts:
        - asset: assets/GoogleSansRegular.ttf
