name: myportfolio
description: My profolio page.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Added explicit version
  url_strategy: ^0.3.0 # Updated from ^0.2.0
  layout: ^1.0.5 # Updated from ^1.0.3
  go_router: ^10.2.0 # Updated from ^10.0.0
  url_launcher: ^6.3.1 # Updated from ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3 # Updated from ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/YClogo.png"
    background_color: "#070707"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
      - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/noto/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/noto/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/noto/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/noto/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/noto/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/noto/NotoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/noto/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/noto/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/noto/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/noto/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/noto/NotoSans-BlackItalic.ttf
          weight: 900
          style: italic
