import 'package:flutter/material.dart';

/// custom icons are prefixed with [ki]
const IconData kiArrowBack = Icons.arrow_back_outlined;
const IconData kiArrowNext = Icons.arrow_forward_outlined;
const IconData kiArrowForward = Icons.arrow_right_alt;
const IconData kiClose = Icons.close;
const IconData kiCircle = Icons.circle_outlined;
const IconData kiMouseScroll = Icons.mouse;
const IconData kiLink = Icons.link;
const IconData kiCode = Icons.code;
const IconData kiFolder = Icons.folder;
const IconData kiChip = Icons.memory;
const IconData kiPhone = Icons.phone_android;
const IconData kiLaptop = Icons.laptop;
const IconData kiTag = Icons.local_offer;
const IconData kiMorning = Icons.wb_sunny;
const IconData kiPerson = Icons.person;
const IconData kiCoding = Icons.computer;
const IconData kiReading = Icons.menu_book;
const IconData kiCoffee = Icons.local_cafe;
const IconData kiMusic = Icons.music_note;
const IconData kiExplore = Icons.explore;
const IconData kiMovie = Icons.movie;
const IconData kiTrophy = Icons.emoji_events;
const IconData kiActivity = Icons.workspace_premium;
const IconData kiMemo = Icons.note;
const IconData kiError = Icons.error_outline;
const IconData kiSuccess = Icons.check_circle_outline;
const IconData kiMail = Icons.mail;
const IconData kiCredit = Icons.star;
const IconData kiHeart = Icons.favorite;
